name: parking_app_cli
description: A command-line Parking application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  # path: ^1.8.0

  # region CLI dependencies

  # !: Generates unique ids
  # Source: https://pub.dev/packages/uuid
  uuid: ^4.4.2
  # !: Validates Swedish social security numbers
  # Source: https://pub.dev/packages/personnummer
  personnummer: ^3.1.0
  # !: Networking
  # Source: https://pub.dev/packages/http
  http: ^1.2.2

  # endregion

  # region Server dependencies

  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

  # endregion

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
