name: client_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  # !: Networking
  # Source: https://pub.dev/packages/http
  http: ^1.2.2

  shared:
    path: ../shared
  shared_client:
    path: ../shared_client

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
