include: package:lints/recommended.yaml

linter:
  rules:
    prefer_relative_imports: true
    avoid_print: true
    prefer_single_quotes: false
    sort_constructors_first: true
    sort_child_properties_last: true
    always_declare_return_types: true

analyzer:
  exclude: [ build/** ]
  language:
    strict-casts: true
    strict-raw-types: true