// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD11oSNcUmdrFS4LsmwBwi9P4TyCMDhdmE',
    appId: '1:761319125381:web:27de9049aca8faa73394ec',
    messagingSenderId: '761319125381',
    projectId: 'parking-app-1ed54',
    authDomain: 'parking-app-1ed54.firebaseapp.com',
    storageBucket: 'parking-app-1ed54.firebasestorage.app',
    measurementId: 'G-QBC8F2V18K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_OFTYgU2eZJ_38MjrGdOOMMd6lzuUGn8',
    appId: '1:761319125381:android:38ab32adf9e4c4483394ec',
    messagingSenderId: '761319125381',
    projectId: 'parking-app-1ed54',
    storageBucket: 'parking-app-1ed54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxKoDtYmvXJ3GfyvEhiIMt8L0bTIC_gFM',
    appId: '1:761319125381:ios:ee2fa3a58825f55d3394ec',
    messagingSenderId: '761319125381',
    projectId: 'parking-app-1ed54',
    storageBucket: 'parking-app-1ed54.firebasestorage.app',
    iosBundleId: 'tech.neurothrone.clientUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxKoDtYmvXJ3GfyvEhiIMt8L0bTIC_gFM',
    appId: '1:761319125381:ios:ee2fa3a58825f55d3394ec',
    messagingSenderId: '761319125381',
    projectId: 'parking-app-1ed54',
    storageBucket: 'parking-app-1ed54.firebasestorage.app',
    iosBundleId: 'tech.neurothrone.clientUser',
  );
}
